### ISSUE TITLE
我这个报错

### ISSUE THREAD

**Issue by 1569099266** [q164749/weixin#2]
G:\weixin>python main.py
Traceback (most recent call last):
  File "G:\weixin\main.py", line 143, in <module>
    accessToken = get_access_token()
  File "G:\weixin\main.py", line 15, in get_access_token
    access_token = get(post_url).json()['access_token']
KeyError: 'access_token'

**Comment by zealzhangz** [comment]
报同样的错误
Traceback (most recent call last):
  File "main.py", line 143, in <module>
    accessToken = get_access_token()
  File "main.py", line 15, in get_access_token
    access_token = get(post_url).json()['access_token']
KeyError: 'access_token'

**Comment by zealzhangz** [comment]
把get(post_url).json()打出来看看，发现是appsecret变了，更新了程序正常

**Comment by yi447780897** [comment]
KeyError: 'access_token'
appsecret过期
刷新微信公众号平台，获取新的appsecret

**Comment by wenwenwen829** [comment]
Traceback (most recent call last):
  File "weixin.py", line 155, in <module>
  File "weixin.py", line 66, in send_message
IndexError: list index out of range
这是啥问题

**Comment by q164749** [comment]
更新一下最新的版本哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月14日(周日) 凌晨0:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [q164749/weixin] 我这个报错 (Issue #2)




 
Traceback (most recent call last):
 File "weixin.py", line 155, in 
 File "weixin.py", line 66, in send_message
 IndexError: list index out of range
 这是啥问题

**Comment by wenwenwen829** [comment]
微信的版本吗
是最新的啊

**Comment by wenwenwen829** [comment]
我刚刚又重新下载重新做了还是这个问题

**Comment by q164749** [comment]
百度云的文件更新了




等到烟火清凉丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "q164749/weixin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月14日(星期天) 凌晨0:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [q164749/weixin] 我这个报错 (Issue #2)





 
我刚刚又重新下载重新做了还是这个问题

**Comment by wenwenwen829** [comment]
每天只能发送一条吗

**Comment by wenwenwen829** [comment]
或者说是只能接收一条

**Comment by q164749** [comment]
你可以做计划任务想发多少条都可以


等到烟火清凉丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "q164749/weixin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月14日(星期天) 凌晨1:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [q164749/weixin] 我这个报错 (Issue #2)





 
每天只能发送一条吗

**Comment by wenwenwen829** [comment]
那为啥我再运行weixin.exe就接收不到了，我和女朋友都只接收到一次

**Comment by q164749** [comment]
可以把文件发我看下




等到烟火清凉丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "q164749/weixin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月14日(星期天) 凌晨1:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [q164749/weixin] 我这个报错 (Issue #2)





 
那为啥我再运行weixin.exe就接收不到了，我和女朋友都只接收到一次

**Comment by wenwenwen829** [comment]
[config.txt](https://github.com/q164749/weixin/files/9331905/config.txt)
