### ISSUE TITLE
程序有一个out_of_range的bug

### ISSUE THREAD

**Issue by A-Li12138** [q164749/weixin#3]
week = week_list[today.isoweekday()] 
是不是应该修改为
 week = week_list[today.isoweekday() % 7] 呢
![image](https://user-images.githubusercontent.com/58163541/184502382-c9b09c5a-9fc3-47dc-bb63-b4f7ebd4b8e5.png)
![image](https://user-images.githubusercontent.com/58163541/184502375-6d0ea4d6-1e9c-4dea-accd-3f290e71de5a.png)

**Comment by q164749** [comment]
是的，你是对的，现在修复一下

**Comment by wenwenwen829** [comment]
多谢大佬、
